DECLARE @SQLCommand VARCHAR(8000),
	@CRLF CHAR(2)=CHAR(13)+CHAR(10)

SELECT @SQLCommand=COALESCE(@SQLCommand+';'+@CRLF,'')
+ 'DROP PROC MetaData.'
+ ROUTINE_NAME
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA='MetaData'
PRINT @SQLCommand
EXEC(@SQLCommand)

SET @SQLCommand = NULL;

SELECT @SQLCommand=COALESCE(@SQLCommand+';'+@CRLF,'')
+ 'DROP VIEW '
+ ' MetaData.'
+ TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA='MetaData'
PRINT @SQLCommand
EXEC(@SQLCommand)

SET @SQLCommand = NULL;

SELECT @SQLCommand=COALESCE(@SQLCommand+';'+@CRLF,'')
+ 'ALTER TABLE MetaData.' 
+ OBJECT_NAME(parent_object_id)
+ ' DROP CONSTRAINT ' 
+ name
FROM sys.foreign_keys
PRINT @SQLCommand
EXEC(@SQLCommand)

SET @SQLCommand = NULL;

SELECT @SQLCommand=COALESCE(@SQLCommand+';'+@CRLF,'')
+ 'DROP TABLE '
+ ' MetaData.'
+ TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='MetaData'
AND TABLE_TYPE='BASE TABLE'
PRINT @SQLCommand
EXEC(@SQLCommand)
